name: Build and Release

on:
  push:
    branches: 
      - "main"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Prepare artifact (Linux)
        run: |
          mkdir -p "./artifact/linux/Elite Dangerous Binding Switcher/bindings/"
          chmod +x ./bin/edbs
          mv ./bin/edbs "./artifact/linux/Elite Dangerous Binding Switcher/"
          cp ./README.md "./artifact/linux/Elite Dangerous Binding Switcher/README.md"

      - name: Prepare artifact (Windows)
        run: |
          mkdir -p "./artifact/win32/Elite Dangerous Binding Switcher/bindings/"
          mv ./bin/edbs.exe "./artifact/win32/Elite Dangerous Binding Switcher/"
          cp ./README.md "./artifact/win32/Elite Dangerous Binding Switcher/README.md"

      - name: Compress artifact (Linux)
        run: |
          cd artifact/linux/
          upx "./Elite Dangerous Binding Switcher/edbs"
          tar -cvzf edbs-linux.tar.gz "./Elite Dangerous Binding Switcher/"

      - name: Compress artifact (Windows)
        run: |
          cd artifact/win32/
          upx "./Elite Dangerous Binding Switcher/edbs.exe"
          zip -r edbs-win.zip "./Elite Dangerous Binding Switcher/"

      - name: Create Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            artifact/linux/edbs-linux.tar.gz
            artifact/win32/edbs-win.zip